// <auto-generated />
using System;
using ControleTarefas.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleTarefas.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220618234350_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ControleTarefas.Business.Models.Tarefa", b =>
                {
                    b.Property<int>("CodTarefa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodTarefa"), 1L, 1);

                    b.Property<int>("CodTarefaPrioridade")
                        .HasColumnType("int");

                    b.Property<int>("CodTarefaStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataInsercao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR(250)")
                        .HasColumnName("Descricao");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR(80)")
                        .HasColumnName("Titulo");

                    b.HasKey("CodTarefa");

                    b.HasIndex("CodTarefaPrioridade");

                    b.HasIndex("CodTarefaStatus");

                    b.HasIndex(new[] { "CodTarefa" }, "I_Tarefa_CodTarefa")
                        .IsUnique();

                    b.ToTable("Tarefa", (string)null);
                });

            modelBuilder.Entity("ControleTarefas.Business.Models.TarefaPrioridade", b =>
                {
                    b.Property<int>("CodTarefaPrioridade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodTarefaPrioridade"), 1L, 1);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodTarefaPrioridade");

                    b.ToTable("TarefaPrioridade");
                });

            modelBuilder.Entity("ControleTarefas.Business.Models.TarefaStatus", b =>
                {
                    b.Property<int>("CodTarefaStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodTarefaStatus"), 1L, 1);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodTarefaStatus");

                    b.ToTable("TarefasStatus");
                });

            modelBuilder.Entity("ControleTarefas.Business.Models.Tarefa", b =>
                {
                    b.HasOne("ControleTarefas.Business.Models.TarefaPrioridade", "TarefaPrioridade")
                        .WithMany()
                        .HasForeignKey("CodTarefaPrioridade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleTarefas.Business.Models.TarefaStatus", "TarefaStatus")
                        .WithMany()
                        .HasForeignKey("CodTarefaStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TarefaPrioridade");

                    b.Navigation("TarefaStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
